# Generated by Django 5.2.4 on 2025-07-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shoper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.TextField(max_length=50)),
                ('cpassword', models.TextField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='shop',
        ),
    ]
