# Generated by Django 5.2.4 on 2025-07-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_shoper_delete_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoper',
            name='cpassword',
        ),
    ]
