# Generated by Django 5.2.4 on 2025-07-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_shoper_cpassword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shoper',
            new_name='user',
        ),
    ]
