# Generated by Django 5.2.4 on 2025-08-28 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_main_catagory_product_main_catagory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.TextField()),
                ('otp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sub_catagory',
            name='main_catagory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Sub_catagory',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Main_catagory',
            new_name='Main_category',
        ),
        migrations.RenameModel(
            old_name='Main_catagory',
            new_name='Main_category',
        ),
        migrations.AddField(
            model_name='sub_category',
            name='Main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.main_category'),
        ),
        migrations.AddField(
            model_name='product',
            name='Sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.sub_category'),
        ),
        migrations.DeleteModel(
            name='Sub_catagory',
        ),
    ]
