# Generated by Django 5.2.4 on 2025-08-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_sub_catagory_user_delete_register_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_catagory',
            new_name='Main_catagory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_catagory',
            new_name='Sub_catagory',
        ),
    ]
