# Generated by Django 5.2.4 on 2025-08-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_catagory',
            old_name='main_catagory',
            new_name='Main_catagory',
        ),
    ]
