# Generated by Django 5.2.4 on 2025-08-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_main_catagory_sub_catagory_main_catagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main_catagory',
            new_name='Main_category',
        ),
        migrations.RenameModel(
            old_name='Sub_catagory',
            new_name='Sub_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Main_catagory',
            new_name='Main_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Sub_catagory',
            new_name='Sub_category',
        ),
        migrations.RenameField(
            model_name='sub_category',
            old_name='Main_catagory',
            new_name='Main_category',
        ),
    ]
