# Generated by Django 5.2.4 on 2025-09-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_add_cart_delete_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_cart',
            old_name='Product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='add_cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
