# Generated by Django 5.2.4 on 2025-09-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_product_id_add_cart_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_cart',
            old_name='product',
            new_name='Product_id',
        ),
        migrations.RenameField(
            model_name='add_cart',
            old_name='user',
            new_name='user_id',
        ),
    ]
