# Generated by Django 5.2.4 on 2025-09-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_product_add_cart_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_cart',
            old_name='Product_id',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='add_cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
